Closes #2. Env var KEEP_TRANSCODE added.

diff --git a/subsonic/root/var/cache/scripts/template b/subsonic/root/var/cache/scripts/template
--- a/subsonic/root/var/cache/scripts/template
+++ b/subsonic/root/var/cache/scripts/template
@@ -7,6 +7,7 @@ APP_NAME="APP_NAME"
 APP_USER=${APP_USER:-$USER}
 APP_REPO=${APP_REPO:-hurricane}
 APP_CONFIG=${APP_CONFIG:-"/home/${APP_USER}/.${APP_NAME}"}
+KEEP_TRANSCODE=${KEEP_TRANSCODE:-"false"}
 
 ( id -Gn | grep -q docker ) || [ $EUID == 0 ] || SUDO=sudo
 
@@ -51,6 +52,7 @@ prepare_docker_env_parameters() {
   ENV_VARS+=" --env=APP_GID=${APP_GID}"
   ENV_VARS+=" --env=TZ=$(cat /etc/timezone)"
   ENV_VARS+=" --env=APP_USER=${APP_USER}"
+  ENV_VARS+=" --env=KEEP_TRANSCODE=${KEEP_TRANSCODE}"
   if [ -f /etc/timezone ]; then
     ENV_VARS+=" --env=TZ=$(cat /etc/timezone)"
   else
@@ -67,6 +69,42 @@ prepare_docker_volume_parameters() {
   VOLUMES+=" --volume=${APP_CONFIG}:/config"
 }
 
+prepare_user_volume_parameters() {
+  # Ensure subsonic host APP_CONFIG  directory exist.
+  if [ ! -d "${APP_CONFIG}" ]; then
+    echo "Error, Subsonic data directory: ${APP_CONFIG} does not exist."
+    exit 1
+  fi
+
+  VOLUMES_CONFIG="${APP_CONFIG}/.dockervolumes"
+  if [ ! -e "$VOLUMES_CONFIG" ]; then
+    declare -a user_volumes
+    echo "No existing user defined data volumes found."
+    echo "Please enter any directory paths you wish to be accessible "
+	echo "from the containerized environment, one entry per line."
+    echo "Enter \"done\" when finished"
+    while read mediapath; do
+      if [ "$mediapath" == "done" ]; then
+        break
+      fi
+      if [ ! -d "$mediapath" ]; then
+        echo "Sorry, $mediapath is not a valid path."
+      else
+        user_volumes+=("$mediapath")
+      fi
+    done < /dev/stdin
+
+    for user_volume in "${user_volumes[@]}"; do
+      echo "${user_volume}" >> "${VOLUMES_CONFIG}"
+    done
+  fi
+
+  # setup user volumes
+  while read user_volume; do
+    VOLUMES+=" --volume=${user_volume}:${user_volume}"
+  done < "$VOLUMES_CONFIG"
+}
+
 prog=$(basename $0)
 if [[ ${prog} == "${APP_NAME}" ]]; then
   [ "${1}" == "bash" ] && \
@@ -78,6 +116,7 @@ fi
 cleanup_stopped_instances
 prepare_docker_env_parameters
 prepare_docker_volume_parameters
+prepare_user_volume_parameters
 
 if [ ${running} ]; then
   echo "Already running."
